version: '3.4'

services:

  mysql-db:
    container_name: mysql_prodsmart
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: password
    ports: 
      - "3307:3306"

  server:
    build: ./server
    depends_on:
      - mysql-db
    container_name: server_prodsmart
    environment:
      - DB_HOST=mysql-db
      - DB_USER=prodsmart
      - DB_PASSWORD=password
      - DB_NAME=prodsmart
      - DB_PORT=3306
    ports:
      - "7000:8000"
    volumes:
      - ./server:/app
  
  client:
    build: ./client
    container_name: client_prodsmart
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
